import { Eventu } from "./eventu";
import { Koligasaun } from "./koligasaun";
import { Aldeia } from "./lokal/aldeia";
import { Partidu } from "./partidu";

export interface KampanaEleitoral {
    id: number;
    eventu: Eventu;
    partidu: Partidu;
    koligasaun: Koligasaun;
    fatinKampana: string;
    aldeia: Aldeia;
    naranPartiduKoligasaun: string;
    orariuKampana: Date;
    naranOfisialMonitorizasaun: string;
    numeruPartisipante: number;
    persentajenFeto: number;
    persentajenMane: number;
    numeruIntervensaunFeto: number;
    tuirOrariuKalendariu: boolean;
    esplikasaunTuirOrariuKalendariu: string;
    formaPasifika: boolean;
    esplikasaunFormaPasifika: string;
    impedimentuHusiEma: boolean;
    esplikasaunImpedimentuHusiEma: string;
    impedimentuHusiGrupuPartidu: boolean;
    esplikasaunImpedimentuHusiGrupuPartidu: string;
    eventuLaTuirOras: boolean;
    esplikasaunEventuLaTuirOras: string;
    halaoFatinBandu: boolean;
    esplikasaunHalaoFatinBandu: string;
    uzaPatrimonioEstadu: boolean;
    esplikasaunUzaPatrimonioEstadu: string;
    asaunDiskriminasaun: boolean;
    esplikasaunAsaunDiskriminasaun: string;
    detensaunPrizaun: boolean;
    esplikasaunDetensaunPrizaun: string;
    hetanApoiuForsaMembruGovernu: boolean;
    esplikasaunHetanApoiuForsaMembruGovernu: string;
    formaDesrespeitu: boolean;
    esplikasaunFormaDesrespeitu: string;
    impedeDistribuisaunSasan: boolean;
    esplikasaunImpedeDistribuisaunSasan: string;
    estragaSasan: boolean;
    esplikasaunEstragaSasan: string;
    faheSasanProvokaViolensia: boolean;
    esplikasaunFaheSasanProvokaViolensia: string;
    tipuLinguajenProvokaViolensia: boolean;
    esplikasaunTipuLinguajenProvokaViolensia: string;
    tipuLinguajenDifamatoria: boolean;
    esplikasaunTipuLinguajenDifamatoria: string;
    tipuLinguajenIntimidaVotante: boolean;
    esplikasaunTipuLinguajenIntimidaVotante: string;
    ameasauGrupuEma: boolean;
    esplikasaunAmeasauGrupuEma: string;
    insultaEstadu: boolean;
    esplikasaunInsultaEstadu: string;
    partiduBanduUzaViolensia: boolean;
    esplikasaunPartiduBanduUzaViolensia: string;
    distribuiRumaMotivaViolensia: boolean;
    esplikasaunDistribuiRumaMotivaViolensia: string;
    incidenteGrave: boolean;
    esplikasaunIncidenteGrave: string;
    apresiasaunJeral: "diak" | "diak tebes" | "at" | "at loos";
    pontosFocaisMonitoriza: boolean;
    mensajenPrinsipal: string;
    ofisialMonitorizasaunHaloMonitorizasaun: boolean;
    komentariu: string;
    estimasaunPartisipante: {
        id: number;
        numeruPartisipante: number;
        persentajenFeto: number;
        persentajenMane: number;
        numeruIntervensaunFeto: number;
    },
    tipuKampana: {
        id: number;
        esplikasaun: string;
        tipu: string;
    }
}
